# Generated by Django 4.2.5 on 2023-10-04 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('info', models.TextField(blank=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
